<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Haam909.CiDummy.Calc</PackageId>
    <RepositoryUrl>https://github.com/Haam909/ci-dummy-dotnet</RepositoryUrl>
  </PropertyGroup>

</Project>
